# Generated by Django 5.1.15 on 2026-05-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpolicy',
            name='object_info',
            field=models.CharField(max_length=200, verbose_name='Объект'),
        ),
    ]
