# Generated by Django 5.1.15 on 2026-04-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('city', models.CharField(max_length=80, verbose_name='Город')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('map_link', models.URLField(blank=True, verbose_name='Ссылка на карту')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='InsuranceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.CharField(choices=[('auto', 'Автострахование'), ('life', 'Жизнь'), ('home', 'Имущество / дом'), ('travel', 'Путешествия')], max_length=20, unique=True, verbose_name='Категория')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Что нужно делать')),
                ('phone_to_call', models.CharField(blank=True, max_length=40, verbose_name='Телефон для звонка')),
            ],
            options={
                'verbose_name': 'Страховой случай',
                'verbose_name_plural': 'Страховые случаи',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('company_name', models.CharField(default='ManasInsurance', max_length=120, verbose_name='Название компании')),
                ('hero_title', models.CharField(default='Будь под надёжной защитой', max_length=200, verbose_name='Заголовок героя')),
                ('hero_subtitle', models.CharField(default='Страхование жизни, авто, имущества и путешествий по всему Кыргызстану', max_length=300, verbose_name='Подзаголовок')),
                ('phone', models.CharField(default='+996 (312) 00-00-00', max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(default='info@manasinsurance.kg', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='г. Бишкек, пр. Чуй 100', max_length=200, verbose_name='Адрес')),
                ('about_short', models.TextField(default='ManasInsurance — современное страховое агентство Кыргызстана. Защищаем то, что важно: вашу жизнь, семью, авто и бизнес.', verbose_name='Кто мы (кратко)')),
                ('about_full', models.TextField(default='Компания ManasInsurance работает на рынке страхования с 2010 года. За это время мы помогли более 50 000 клиентам по всей стране.', verbose_name='О нас подробно')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
