# Generated by Django 5.1.15 on 2026-04-27 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-имя')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('price_from', models.PositiveIntegerField(default=0, verbose_name='Цена от, сом')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('kind', models.CharField(choices=[('osago', 'ОСАГО'), ('kasko', 'КАСКО'), ('dsago', 'ДСАГО'), ('accident', 'Страхование от несчастного случая')], max_length=20, unique=True, verbose_name='Вид')),
                ('has_calculator', models.BooleanField(default=False, verbose_name='Есть калькулятор')),
            ],
            options={
                'verbose_name': 'Автопродукт',
                'verbose_name_plural': 'Автопродукты',
            },
        ),
        migrations.CreateModel(
            name='TariffRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('label', models.CharField(max_length=200, verbose_name='Параметр')),
                ('value', models.CharField(max_length=200, verbose_name='Значение / цена')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='auto.autoproduct')),
            ],
            options={
                'verbose_name': 'Тариф (строка)',
                'verbose_name_plural': 'Тарифы (строки)',
                'ordering': ['order'],
            },
        ),
    ]
