# Generated by Django 5.1.15 on 2026-04-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-имя')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('price_from', models.PositiveIntegerField(default=0, verbose_name='Цена от, сом')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('kind', models.CharField(choices=[('property', 'Имущество компаний'), ('dms', 'Добровольное медицинское страхование'), ('bank', 'Страхование банковской деятельности'), ('liability', 'Обязательные виды страхования гражданской ответственности')], default='property', max_length=20, verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Корпоративный продукт',
                'verbose_name_plural': 'Корпоративные продукты',
            },
        ),
    ]
