# Generated by Django 5.1.15 on 2026-05-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_tech_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО / Компания'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tech_passport',
            field=models.ImageField(blank=True, help_text='Загрузите фото тех. паспорта при автостраховании.', null=True, upload_to='tech_passports/', verbose_name='Тех. паспорт (для авто)'),
        ),
    ]
